#stuff http://about.travis-ci.org/docs/

#Default test script = "npm test"
language: node_js
addons:
    apt:
        packages:
            - build-essential
node_js:
  - '11'

before_install:
    - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    - curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
    - cd zsh-5.0.7
    - ./configure --prefix=$LOCAL
    - make
    - make install
    - cd -
    - export PATH="$LOCAL/bin:$PATH"
    - npm install

script:
  - npm run lint
  - npm run test
