version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     # build the application image
     - run: export TERM=xterm npm run docker:build
     - run: export TERM=xterm npm run docker:lint
     - run: export TERM=xterm npm run docker:test
